services:
  - type: web
    name: worklife-dashboard-api
    env: node
    plan: starter
    rootDir: server
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    preDeployCommand: npx prisma migrate deploy
