services:
  - type: web
    name: worklife-dashboard-api
    env: node
    plan: starter
    rootDir: server
    branch: main
    autoDeploy: true
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: node dist/index.js
