services:
  - type: web
    name: worklife-dashboard-api
    runtime: node
    plan: starter
    rootDir: server
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    releaseCommand: npx prisma migrate deploy
